"""add_user_roles_remove_all_food_logic

Revision ID: 8cc9bedcf004
Revises: b319f9eab37e
Create Date: 2026-03-08 22:40:21.377551

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cc9bedcf004"
down_revision: str | Sequence[str] | None = "b319f9eab37e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop table if it exists
    try:
        op.drop_table("playing_with_neon")
    except Exception:
        pass  # Table doesn't exist, continue
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("client", "restaurant", name="user_role_enum"),
            nullable=False,
        ),
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users",
        "picture_url",
        existing_type=sa.TEXT(),
        type_=sa.String(length=512),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_users_google_sub"), table_name="users")
    op.create_unique_constraint(None, "users", ["google_sub"])
    op.drop_column("users", "goals")
    op.drop_column("users", "onboarding_completed")
    op.drop_column("users", "sport")
    op.drop_column("users", "sex")
    op.drop_column("users", "activity_level")
    op.drop_column("users", "target_calories")
    op.drop_column("users", "available_foods")
    op.drop_column("users", "needs_nutritional_plan")
    op.drop_column("users", "weight_kg")
    op.drop_column("users", "onboarding_completed_at")
    op.drop_column("users", "height_cm")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "height_cm",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "onboarding_completed_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "weight_kg",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "needs_nutritional_plan", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "available_foods",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column("target_calories", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "activity_level", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("sex", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("sport", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "onboarding_completed",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "goals",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_index(op.f("ix_users_google_sub"), "users", ["google_sub"], unique=True)
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "picture_url",
        existing_type=sa.String(length=512),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "role")
    op.create_table(
        "playing_with_neon",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("value", sa.REAL(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("playing_with_neon_pkey")),
    )
    # ### end Alembic commands ###
